CREATE TABLE [dbo].[SellCars](
  [Id] UNIQUEIDENTIFIER NOT NULL,
  [Make] NVARCHAR(250) NOT NULL,
  [Model] NVARCHAR(250) NOT NULL,
  [Year] NUMERIC NOT NULL,
    CONSTRAINT [PK_SelLCars] PRIMARY KEY ([Id]),
)
